### ISSUE TITLE
Querying NPD dataset scaled to 100

### ISSUE THREAD

**Issue by damilolah** [ontop/npd-benchmark#2]
Hello,

I recently used the VIG data generator to increase the npd dataset. I used a scale of 100. I got a csv files which when converted to .nt format it was 25GB. 

However, when I run queries 01.q-10.q you provided, on the original dataset, I get a lot of items returned but for the generated data it returns 0 items. 

I'm using stardog to query my dataset.
Please help.

**Comment by tirrolo** [comment]
Dear Ruth,

you should use the obda-mixer to get the queries instantiated with the 
correct values. However, the current release does not really support 
stardog. You might either try the version in the develop branch, or wait 
for the next release, that will be after next week.

Best regards, Davide.

**Comment by tirrolo** [comment]
Closed because the issue has been addressed in the latest version of mixer.
